### ISSUE TITLE
Multiselect bar is inserted between toolbar and inline filter

### ISSUE THREAD

**Issue by christinebrandel** [blackbaud/skyux-list-builder-view-grids#46]
### Expected behavior
Order should be:  toolbar > inline filter bar > multiselect bar > list view

### Actual behavior
Current order is: toolbar >  multiselect bar > inline filter bar > list view

### Steps to reproduce
<sky-list> with:

<sky-list-toolbar> 
<sky-filter-inline>
 <sky-list-view-grid [enableMultiselect]="true>

### Severity
low

**Comment by Blackbaud-TrevorBurch** [comment]
Did some research and it appears this was due to `sky-filter-inline` being used instead of `sky-list-filter-inline`. Closing for now - if this comes up again for anyone else please reopen.
