### ISSUE TITLE
List view grid with multiselect - 'Only show selected items' check box selects all of the items in a list when unchecked after performing some actions. 

### ISSUE THREAD

**Issue by Blackbaud-NitishSharma** [blackbaud/skyux-list-builder-view-grids#54]
### Expected behavior
'Only show selected items' checkbox should always show selected items in a list.

### Actual behavior
if we first **Select all** and then check **Only show selected items** checkbox
then click **Clear all**
now when you uncheck **Only show selected items** checkbox
it selects all of the items in a list which should not be the behavior.

### Steps to reproduce
1. Go to Demo --> List view grid with multiselect available at  https://developer.blackbaud.com/skyux/components/list/grid 
2. click **Select all** 
3. check **Only show selected items** checkbox
4. click **Clear all**
5. uncheck **Only show selected items** checkbox

it selects all of the items in a list which should not be the behavior.
### Severity
High
### Impact
This is happening in a library(skyux-lib-spa-grantmaking) used by our grantmaking spa(skyux-spa-gmk).

**Comment by Blackbaud-AlexKingman** [comment]
Some more information: The `cancelLastRequest` subject in `list.component.ts` seems to be part of the problem here. If you remove it all together, the filtering works as expected.
