### ISSUE TITLE
When multiSelect enabled, checkboxes are slow to respond

### ISSUE THREAD

**Issue by RARowe** [blackbaud/skyux-list-builder-view-grids#58]
### Expected behavior
When I click a checkbox in a `sky-list-view-grid`, it should immediately be checked. When I click `Select all`, all rows should be immediately checked.
### Actual behavior
When I click a checkbox in a grid, it takes a little more than half a second to show as being checked. When I click `Select all`, it can sometimes take 2 seconds to check all the boxes.
### Steps to reproduce
1. In a `sky-list-view-grid` set `enableMultiSelect` to `true`
2. Click on a checkbox
### Severity
It is still usable, but the performance is very poor.
### Impact
We use a lot of checking/unchecking, so this will be a bad performance issue as time goes on.

I have personally tried changing the `changeDetection` to `OnPush`, but that didn't work.

**Comment by Blackbaud-AlexKingman** [comment]
Hi @RARowe, could you provide some code examples showing this issue? We are having trouble replicating. Thanks!

**Comment by RARowe** [comment]
@Blackbaud-AlexKingman From my personal code, or is there a stackblitz, or equivalent, platform I could create it on?

**Comment by Blackbaud-AlexKingman** [comment]
@RARowe You can either copy+paste the snippet here, or DM me a link to your branch.

**Comment by Blackbaud-AlexKingman** [comment]
Addressed in `@skyux/list-builder@3.6.3`, and `@skyux/list-builder-view-grids@3.6.2`. If you update your dependencies for these two repos, grid performance should be better.
