### ISSUE TITLE
Dragging right-most column to the left shows background

### ISSUE THREAD

**Issue by Blackbaud-markarita** [blackbaud/skyux-list-builder-view-grids#62]
### Expected behavior
Right-most column can't be pulled left to reveal background

### Actual behavior
Dragging right-most column to the left shows the background, which may be a different color from the foreground/dragged column

### Steps to reproduce
Drag left or right vertical bar of right-most column to the left in a list grid

### Severity
Low

### Impact
Low

**Comment by Blackbaud-SteveBrush** [comment]
Thanks for the issue! This is working as intended because the right-most column needs to be resizable. We did a little research with other grid components and they operate similarly.
