### ISSUE TITLE
Using template inside of sky-grid-column element causes page to go unresponsive

### ISSUE THREAD

**Issue by Blackbaud-BrianBlanchard** [blackbaud/skyux-list-builder-view-grids#80]
### Expected behavior

Defining a template inside of a sky-grid-column element works correctly.

### Actual behavior

Page becomes unresponsive and the tab must be closed.  

### Steps to reproduce
Use the following snippet as an example.  
Serving locally (`skyux serve`) works fine, but running off build will reproduce the problem (`skyux build -s`).
```
<sky-grid-column id="failed" field="failed" heading="Failed">
  <ng-template let-row="row">
	<i *ngIf="row.failed" class="fa fa-exclamation-triangle"></i>
  </ng-template>
</sky-grid-column>
```
### Severity
 
High

### Impact

High

**Comment by Blackbaud-TrevorBurch** [comment]
In `skyux/grids` version `4.0.5` and `skyux/list-builder-view-grids` version `4.0.2`
