### ISSUE TITLE
User is facing issue while rearranging grid headers

### ISSUE THREAD

**Issue by vishal121212121212112** [blackbaud/skyux-list-builder-view-grids#87]
Expected behavior : Column should be rearranged as per the selection

Actual behavior : User is not able to rearrange the column until and unless cursor is on the blank or white space of grid header

Steps to reproduce : Try to drag  column header from its text, it will not be dragged but works by dragging from space in header

Severity : Medium

I am attaching video this issue.
[Header Rearranging Issue.zip](https://github.com/blackbaud/skyux-list-builder-view-grids/files/5050775/Header.Rearranging.Issue.zip)

[AB#1547619](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1547619)

**Comment by Blackbaud-TrevorBurch** [comment]
In `@skyux/grids` version `4.0.4`
